PHYSICSENGINE: Vector2d Class Reference
Vector2d Class Reference
#include <vector2d.h>
Public Member Functions
Vector2d (double _x, double _y)
Vector2d operator* (double _scalar)
Vector2d operator+ (Vector2d _v)
Vector2d operator- (Vector2d _v)
Vector2d operator/ (Vector2d _v)
bool operator== (Vector2d _v)
bool operator>= (Vector2d _v)
bool operator<= (Vector2d _v)
bool operator> (Vector2d _v)
bool operator< (Vector2d _v)
Public Attributes
double m_x = 0
double m_y = 0
Detailed Description
Definition at line 5 of file vector2d.h.
Constructor & Destructor Documentation
Vector2d::Vector2d (double _x, double _y)
Definition at line 3 of file vector2d.cpp.
References m_x, and m_y.
 {
     m_x = _x;
     m_y = _y;
 }
Member Function Documentation
Vector2d Vector2d::operator* (double _scalar)
Definition at line 8 of file vector2d.cpp.
References m_x, m_y, and Vector2d().
 {
     return Vector2d(m_x*_scalar, m_y*_scalar);
 }
Vector2d Vector2d::operator+ (Vector2d _v)
Definition at line 12 of file vector2d.cpp.
References m_x, m_y, and Vector2d().
 {
     return Vector2d(m_x+_v.m_x, m_y+_v.m_y);
 }
Vector2d Vector2d::operator- (Vector2d _v)
Definition at line 16 of file vector2d.cpp.
References m_x, m_y, and Vector2d().
 {
     return Vector2d(m_x-_v.m_x, m_y-_v.m_y);
 }
Vector2d Vector2d::operator/ (Vector2d _v)
Definition at line 20 of file vector2d.cpp.
References m_x, m_y, and Vector2d().
 {
     return Vector2d(m_x/_v.m_x, m_y/_v.m_y);
 }
bool Vector2d::operator< (Vector2d _v)
Definition at line 42 of file vector2d.cpp.
References m_x, and m_y.
 {
     return ((m_x == _v.m_x)<(m_y == _v.m_y));
 }
bool Vector2d::operator<= (Vector2d _v)
Definition at line 33 of file vector2d.cpp.
References m_x, and m_y.
 {
     return (((m_x == _v.m_x)&&(m_y == _v.m_y))
          || ((m_x == _v.m_x)<(m_y == _v.m_y)));
 }
bool Vector2d::operator== (Vector2d _v)
Definition at line 24 of file vector2d.cpp.
References m_x, and m_y.
 {
     return ((m_x == _v.m_x)&&(m_y == _v.m_y));
 }
bool Vector2d::operator> (Vector2d _v)
Definition at line 38 of file vector2d.cpp.
References m_x, and m_y.
 {
     return ((m_x == _v.m_x)>(m_y == _v.m_y));
 }
bool Vector2d::operator>= (Vector2d _v)
Definition at line 28 of file vector2d.cpp.
References m_x, and m_y.
 {
     return (((m_x == _v.m_x)&&(m_y == _v.m_y))
          || ((m_x == _v.m_x)>(m_y == _v.m_y)));
 }
Member Data Documentation
double Vector2d::m_x = 0
Definition at line 9 of file vector2d.h.
double Vector2d::m_y = 0
Definition at line 10 of file vector2d.h.
The documentation for this class was generated from the following files:
vector2d.h
vector2d.cpp