PHYSICSENGINE: World Class Reference
World Class Reference
The Scene class, contains all the collision code.
#include <world.h>
Public Member Functions
World ()
World::World Constructor and sets the starting shape size.
virtual ~World ()
World::~World destructorize this thing. Make sure to eliminate dynamically allocated memory.
virtual void init ()
World::init initialises the GL World, enabling features that are needed.
virtual void resize (int w, int h)
World::resize needs to set up the camera paramaters (i.e. projection matrix) and the viewport.
virtual void draw ()
World::draw Draws the World to the current GL context.
void updateObjectsPos ()
World::updateObjectsPos This updates the position of the objects once the velocities have been updated.
void updateObjectsVel ()
World::updateObjectsVel This calls all of the velocity changing functions and handles the timer.
Public Attributes
std::vector< GameObject * > m_masterList
m_masterList The list that contains all GameObjects in the scene
bool m_xray = true
m_xray This bool allows for the swapping between the 'solid and 'hollow' draw methods
bool m_gravOn = true
m_gravOn This bool allows for turning gravity on and off
bool m_shapeSwitch = true
m_shapeSwitch This changes which shape is created on the left click or space bar
int m_calcs = 5
m_calcs This is how many times the objects are updated before drawing
int m_shapeSize = 5
m_shapeSize This is changes the GameObject.m_radMod during runtime via the arrow keys or UI
double m_startTime
m_startTime This is used for
double m_elapsedTime
m_
Private Member Functions
void collisionDetection ()
World::collisionDetection Detects whether two objects are colliding, then calls the reaction if they are.
void calcVelX ()
World::calcVelX This calculates the X velocity, and keeps it in the x bounds.
void calcVelY ()
World::calcVelY This calculates the Y velocity, and keeps it in the y bounds (with room for buttons at the top)
void reaction (int _i, double _hyp, double _massRat, double _dX, double _dY)
Wolrd::reaction This applies the reaction forces to the shapes.
Private Attributes
bool m_isInit
m_isInit Used for a sanity check, making sure the world is initialised before continuing
Detailed Description
The Scene class, contains all the collision code.
This class is the backbone of the program, it handles the SDL/GL window and rendering and the collision detection, and reaction for the objects.
Author
Tom Hoxey & Richard Southern
Version
1.0
Date
28/04/16
Definition at line 15 of file world.h.
Constructor & Destructor Documentation
World::World ()
World::World Constructor and sets the starting shape size.
Definition at line 7 of file world.cpp.
References m_shapeSize.
              : m_startTime(0.0),m_elapsedTime(0.0),m_isInit(false)
 {
     m_shapeSize = 5;
 }
World::~World () virtual
World::~World destructorize this thing. Make sure to eliminate dynamically allocated memory.
Definition at line 12 of file world.cpp.
 {}
Member Function Documentation
void World::calcVelX () private
World::calcVelX This calculates the X velocity, and keeps it in the x bounds.
Definition at line 93 of file world.cpp.
References BOUND, and m_masterList.
 {
     for(auto& i : m_masterList)
     {
         if(i->m_posX > BOUND-i->m_radius)
         {
             i->m_posX = BOUND-i->m_radius;
             i->m_velX *= i->m_bounce;
         }
         else if(i->m_posX < -BOUND+i->m_radius)
         {
             i->m_posX = -BOUND+i->m_radius;
             i->m_velX *= i->m_bounce;
         }
     }
 }
void World::calcVelY () private
World::calcVelY This calculates the Y velocity, and keeps it in the y bounds (with room for buttons at the top)
Definition at line 110 of file world.cpp.
References BOUND, m_gravOn, and m_masterList.
 {
     for(auto& i : m_masterList)
     {
         if(i->m_posY >  (BOUND-0.1)-i->m_radius) //0.1 left for UI
         {
             i->m_posY = (BOUND-0.1)-i->m_radius;
             i->m_velY *= i->m_bounce;
         }
         else if(i->m_posY < -BOUND+i->m_radius)
         {
             i->m_posY = -BOUND+i->m_radius;
             i->m_velY *= i->m_bounce;
         }
         if(m_gravOn)
         {
             i->m_velY -= i->m_g/5;
         }
     }
 }
void World::collisionDetection () private
World::collisionDetection Detects whether two objects are colliding, then calls the reaction if they are.
Definition at line 45 of file world.cpp.
References m_masterList, and reaction().
 {
     for(uint16_t i = 0; i < m_masterList.size(); ++i)
     {
         for(uint16_t j = i+1; j < m_masterList.size(); ++j) //Nested loop to only compare collisions once i.e A -> B and not B -> A as well
         {
             if( m_masterList[i]->m_isCircle && m_masterList[j]->m_isCircle)
             {
                 double dX = m_masterList[i]->m_posX - m_masterList[j]->m_posX;
                 double dY = m_masterList[i]->m_posY - m_masterList[j]->m_posY;
                 double sumOfRads = m_masterList[i]->m_radius + m_masterList[j]->m_radius;  //Note to self:DONT change these to floats again, it will break it... again
                 double massRatI = m_masterList[i]->m_mass/(m_masterList[i]->m_mass+m_masterList[j]->m_mass);
                 double massRatJ = 1-massRatI; //Should be m_masterList[j]->m_mass/(m_masterList[i]->m_mass+m_masterList[j]->m_mass) but faster this way
                 double sumOfSquares = sqrt((dX*dX)+(dY*dY));
                 double hyp = asin(dY/sumOfSquares)*(sumOfRads-sumOfSquares);
                 if(hyp == 0)
                     hyp = 0.001; //Just in case
                 if(sumOfRads > sumOfSquares)
                 {
                     if(m_masterList[i]->m_isDynamic)
                     {
                         reaction(i, hyp, massRatI, dX, dY);
                     }
                     if(m_masterList[j]->m_isDynamic)
                     {
                         reaction(j, -hyp, -massRatJ, -dX, -dY);
                     }
                 }
                 else
                 {
                     m_masterList[j]->m_isColliding = false;
                 }
             }
             //WORK IN PROGRESS
 //            else if(m_masterList[i]->m_isCircle && !m_masterList[j]->m_isCircle)
 //            {
 //                float circleX = m_masterList[i]->m_posX;
 //                float lineX1 = m_masterList[j]->m_posX;
 //                float lineX2 = m_masterList[j]->m_posX2;
 //                float lineY1 = m_masterList[j]->m_posY;
 //                float lineY2 = m_masterList[j]->m_posY2;
 //                float lineVec1 = lineX1-lineY1;
 //                float lineVec2 = lineX2-lineY2;
 //            }
         }
     }
 }
void World::draw () virtual
World::draw Draws the World to the current GL context.
Definition at line 38 of file world.cpp.
References m_isInit.
                  {
     if (!m_isInit) return;
     // Clear the display buffer
     glClear(GL_DEPTH_BUFFER_BIT | GL_COLOR_BUFFER_BIT);
 }
void World::init () virtual
World::init initialises the GL World, enabling features that are needed.
Definition at line 14 of file world.cpp.
References m_isInit, and m_startTime.
 {
     if (m_isInit) return;
     glFrontFace(GL_CCW);
     glEnable(GL_NORMALIZE);
     // Set the background colour
     glClearColor(0.5f, 0.5f, 0.5f, 1.0f);
     // Set our start time by using the gettimeofday function (accurate to 10 nanosecs)
     struct timeval tim;
     gettimeofday(&tim, NULL);
     m_startTime = tim.tv_sec+(tim.tv_usec * 1e-6);
     m_isInit = true;
 }
void World::reaction (int _i, double _hyp, double _massRat, double _dX, double _dY) private
Wolrd::reaction This applies the reaction forces to the shapes.
Parameters
_i The number in the master list of the object reacting
_hyp The distance of intersection of the two objects
_massRat The ratio of the masses, which are semi-random and based on size
_dX The distance between the centres of the shapes on the x axis
_dX The distance between the centres of the shapes on the y axis
Definition at line 157 of file world.cpp.
References DAMPNER, and m_masterList.
 {
     m_masterList[_i]->m_isColliding = true;
     m_masterList[_i]->m_posX += _dX*DAMPNER; //Stops overlap being possible
     m_masterList[_i]->m_velX += _hyp*_massRat;
     m_masterList[_i]->m_velX *= _hyp*_massRat*m_masterList[_i]->m_bounce; //Removing _hyp*_massRat cripples performance, confusing
     m_masterList[_i]->m_posY += _dY*DAMPNER;
     m_masterList[_i]->m_velY += _hyp*_massRat;
     m_masterList[_i]->m_velY *= _hyp*_massRat*m_masterList[_i]->m_bounce;
 }
void World::resize (int w, int h) virtual
World::resize needs to set up the camera paramaters (i.e. projection matrix) and the viewport.
Parameters
w Width of window
h Height of window
Definition at line 28 of file world.cpp.
References m_isInit.
 {
     if (!m_isInit) return;
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D(-1.0f, 1.0f, -1.0f, 1.0f);
     glViewport(0,0,w,h);
     glMatrixMode(GL_MODELVIEW);
 }
void World::updateObjectsPos ()
World::updateObjectsPos This updates the position of the objects once the velocities have been updated.
Definition at line 139 of file world.cpp.
References m_calcs, m_elapsedTime, m_masterList, and m_startTime.
 {
     struct timeval tim;
     gettimeofday(&tim, NULL);
     double now =tim.tv_sec+(tim.tv_usec * 1e-6);
     m_elapsedTime = std::abs(m_startTime - now)*1e-12;
     for(auto& i : m_masterList)
     {
         if(i->m_isDynamic)
         {
             if(!isnan(i->m_velX)) //Safety check, can return nan and make object disapear!
                 i->m_posX += (i->m_velX*m_elapsedTime)/m_calcs;
             if(!isnan(i->m_velY))
                 i->m_posY += (i->m_velY*m_elapsedTime)/m_calcs;
         }
     }
 }
void World::updateObjectsVel ()
World::updateObjectsVel This calls all of the velocity changing functions and handles the timer.
Definition at line 131 of file world.cpp.
References calcVelX(), calcVelY(), and collisionDetection().
 {
     //std::cout<<m_startTime<<std::endl;
     calcVelX();
     calcVelY();
     collisionDetection();
 }
Member Data Documentation
int World::m_calcs = 5
m_calcs This is how many times the objects are updated before drawing
Definition at line 43 of file world.h.
double World::m_elapsedTime
m_
Definition at line 49 of file world.h.
bool World::m_gravOn = true
m_gravOn This bool allows for turning gravity on and off
Definition at line 39 of file world.h.
bool World::m_isInit private
m_isInit Used for a sanity check, making sure the world is initialised before continuing
Definition at line 66 of file world.h.
std::vector<GameObject*> World::m_masterList
m_masterList The list that contains all GameObjects in the scene
Definition at line 35 of file world.h.
int World::m_shapeSize = 5
m_shapeSize This is changes the GameObject.m_radMod during runtime via the arrow keys or UI
Definition at line 45 of file world.h.
bool World::m_shapeSwitch = true
m_shapeSwitch This changes which shape is created on the left click or space bar
Definition at line 41 of file world.h.
double World::m_startTime
m_startTime This is used for
Definition at line 47 of file world.h.
bool World::m_xray = true
m_xray This bool allows for the swapping between the 'solid and 'hollow' draw methods
Definition at line 37 of file world.h.
The documentation for this class was generated from the following files:
world.h
world.cpp